### ISSUE TITLE
Update to angular 5 and bootstrap 4

### ISSUE THREAD

**Issue by yakimko** [optimistex/ng2-select-ex#3]

**Comment by optimistex** [comment]
**Upgraded to Angular 5**
Current version: 3.2.1

I don't understand the question about bootstrap. What are you mean?

**Comment by yakimko** [comment]
Currently, you are using classes and glyphicons in the template from the twitter bootstrap 3.*.  
I asked you to use classes from the twitter bootstrap 4.* and font-awesome

**Comment by optimistex** [comment]
Thanks. I understand now.
I consider the classes of bootstrap as a legacy. And thinking about layout.
My Idea is to make layout by BEM: https://en.bem.info/methodology/
And I want to remove all bootstrap's classes. But now I'm just thinking and open to any ideas.

What are you think?

**Comment by optimistex** [comment]
Work by supporting Bootstrap 4 was planned: #5

**Comment by optimistex** [comment]
> I asked you to use classes from the twitter bootstrap 4. and font-awesome
It's done: #5
